### PR TITLE
Code review!

### PR DESCRIPTION
**Pull request by Resisty**
## Unfortunately
this is all untested because I don't have any GPS pictures but at least it doesn't bomb out on the empty set! Yay test-driven development?

## Thoughts:
- explicit module names
- Classes to handle data collection/presentation
- list comprehensions for loops
- default values are good
- removed unused stuff (get_timestamp) (can add back into GPS if needed)
- 80 character lines
- avoid array subscripting when possible
- put constants at top when possible (lines 14-18 clearly an exception, unfortunately)

### CODE REVIEW

**Comment by vigevenoj** [comment]
Merged it and then had a thought before testing- the latitude ref & longitude ref elements need to be checked to see if we have to make the lat or lon negative (instead of positive latitude S, it'd be -latitude)
Running it against a test file I get this exception.

> Traceback (most recent call last):
  File "/Users/vigevenoj/code/scripts/map_my_trip_pics.py", line 108, in <module>
    sys.exit(main())
  File "/Users/vigevenoj/code/scripts/map_my_trip_pics.py", line 103, in main
    if gpsdata.dict
  File "/Users/vigevenoj/code/scripts/map_my_trip_pics.py", line 60, in dict
    'latitude': self.latitude,
  File "/Users/vigevenoj/code/scripts/map_my_trip_pics.py", line 71, in latitude
    return self._gps.latitude
  File "/Users/vigevenoj/code/scripts/map_my_trip_pics.py", line 30, in latitude
    self._compute()
  File "/Users/vigevenoj/code/scripts/map_my_trip_pics.py", line 36, in _compute
    for i in j.values()[0:3]])
TypeError: 'list' object is not callable

I'll see if I can figure that out.

**Comment by Resisty** [comment]
Woops, I dunno why I threw () onto the end of values. Just change line 36 to `for i in j.values[0:3]])`

**Comment by vigevenoj** [comment]
Yep, that worked:
>Jacobs-MacBook-Pro:scripts vigevenoj$ python ~/code/scripts/map_my_trip_pics.py ~/Downloads/amsterdam/
[{"latitude": null, "longitude": null, "filename": "/Users/vigevenoj/Downloads/amsterdam/IMG_20160404_132209.jpg"}]

**Comment by Resisty** [comment]
> latitude": null, "longitude": null,

For some version of "worked". :P

**Comment by vigevenoj** [comment]
>self._latlong: defaultdict(<function <lambda> at 0x109ceaa28>, {'latitude': None, 4589/100: 52.31274722222222, 'longitude': None, 42/5: 4.769})

I had to read about how python handles multiple assignment and looping through multiple lists, but
> degs, mins, secs = ([float(fractions.Fraction(str(i)))
                                  for i in j.values[0:3]])

needs a separate variable in the inner loop,
> degs, mins, secs = ([float(fractions.Fraction(str(x)))
                                  for x in j.values[0:3]])

**Comment by vigevenoj** [comment]
I'm not really sure how to address the GPSLatitudeRef and GPSLongitudeRef in the GPS object as it stands. Thoughts?

**Comment by Resisty** [comment]
See https://github.com/vigevenoj/scripts/pull/4

**Pull request merged**
